title: rust-analyzer
description: "rust-analyzer: building a better Rust IDE"
baseurl: ""
url: "https://rust-analyzer.github.io/"
github_username: rust-analyzer
exclude:
  - wasm-demo/
  - vendor

plugins:
- jekyll-asciidoc
- jekyll-redirect-from

asciidoctor:
  attributes:
    - source-highlighter=rouge
    - source-linenums-option=_
    - rouge-style=github
